### ISSUE TITLE
Invalid Solution - 19.cpp

### ISSUE THREAD

**Issue by sreejeet** [BitsPleaseMSI/BitsPlease-solutions#24] opened 2018-02-06 11:49 UTC
https://github.com/BitsPleaseMSI/BitsPlease-solutions/blob/master/19.cpp does not follow the input format as in the problem statement. Please implement the use of test cases.

**Comment by Bhupesh-V** [comment] 2019-02-23 15:23
@sreejeet 
the issue is now fixed 
Everyone can view the updated code by @Animesh-Ghosh

**Closed as completed** 2019-02-23 15:24 UTC
